Lmod has detected the following error: Warning: Python module not loaded, you
already have Python loaded via conda init. 
While processing the following module(s):
    Module fullname              Module Filename
    ---------------              ---------------
    python/3.9-anaconda-2021.11  /opt/nersc/pe/modulefiles/python/3.9-anaconda-2021.11.lua

cp: cannot stat '/pscratch/sd/d/dpalmer3/mypythonev/lib/python3.11/site-packages/TEGT/parameters/KC_insp_pz.txt_nkp225': No such file or directory
cp: cannot stat '/pscratch/sd/d/dpalmer3/mypythonev/lib/python3.11/site-packages/TEGT/parameters/CH_pz.rebo_nkp225': No such file or directory
LAMMPS (23 Jun 2022)
Reading data file ...
  orthogonal box = (0 0 0) to (21.321545 12.31 33)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  200 atoms
Finding 1-2 1-3 1-4 neighbors ...
  special bond factors lj:    0        0        0       
  special bond factors coul:  0        0        0       
     0 = max # of 1-2 neighbors
     0 = max # of 1-3 neighbors
     0 = max # of 1-4 neighbors
     1 = max # of special neighbors
  special bonds CPU = 0.000 seconds
  read_data CPU = 0.003 seconds
100 atoms in group top
100 atoms in group bottom
ERROR on proc 0: cannot open rebo potential file fit_popov_interlayer_nkp225/CH_pz.rebo_nkp225: No such file or directory (../potential_file_reader.cpp:59)
Last command: pair_coeff      * * rebo fit_popov_interlayer_nkp225/CH_pz.rebo_nkp225 C C
